import assert from 'node:assert/strict'; import test from 'node:test'; import { assertNoOAuthSecrets, canonicalPersistenceKey, normalizeGmailOAuth, scanSensitivePersistenceKeys } from '../src/lib/gmailOAuth'; import { createOAuthWorker } from '../workers/gmail-oauth/src/index'; import { encryptToken, MemorySessionStore, pkce, ProductionSessionStoreAdapter } from '../workers/gmail-oauth/src/security';
test('PKCE uses S256 with secure verifier properties', async () => { const a = await pkce(), b = await pkce(); assert.equal(a.method, 'S256'); assert.match(a.verifier, /^[A-Za-z0-9_-]+$/); assert.ok(a.verifier.length >= 43 && a.verifier.length <= 128); assert.notEqual(a.verifier, b.verifier); assert.notEqual(a.challenge, b.challenge); });
test('state is short lived and replay protected', () => { const store = new MemorySessionStore(); const tx = store.createOAuthTransaction('https://example.test/preview/', 'preview', 'verifier'); assert.equal(store.consumeOAuthTransaction(tx.state).codeVerifier, 'verifier'); assert.throws(() => store.consumeOAuthTransaction(tx.state)); });
test('sessions are audience isolated and encrypted token does not expose plaintext', async () => { const store = new MemorySessionStore(); const id = store.createSession('preview', ['scope']); assert.ok(store.getSession(id, 'preview')); assert.equal(store.getSession(id, 'production'), undefined); store.deleteSession(id); assert.equal(store.getSession(id, 'preview'), undefined); const encrypted = await encryptToken('fake-refresh-token', 'test-key'); assert.equal(encrypted.includes('fake-refresh-token'), false); });
test('production store adapter is explicitly unavailable without a binding', () => { assert.throws(() => new ProductionSessionStoreAdapter().createSession('preview', []), /not_configured/); });
test('routes enforce origin, CSRF, and safe disconnected status', async () => { const worker = createOAuthWorker(new MemorySessionStore()); const env = { GOOGLE_CLIENT_ID: 'replace-with-google-client-id', GOOGLE_CLIENT_SECRET: 'replace-with-google-client-secret', OAUTH_SESSION_SECRET: 'replace', TOKEN_ENCRYPTION_KEY: 'replace', ENVIRONMENT: 'preview', ALLOWED_ORIGINS: 'https://preview.example', ALLOWED_REDIRECTS: 'https://preview.example/app/' };
  const blocked = await worker.fetch(new Request('https://oauth.example/oauth/google/status'), env); assert.equal(blocked.status, 403);
  const status = await worker.fetch(new Request('https://oauth.example/oauth/google/status', { headers: { Origin: 'https://preview.example' } }), env); assert.equal(status.status, 200); const body = await status.json() as { status: string; grantedScopes: string[] }; assert.equal(body.status, 'disconnected'); assert.deepEqual(body.grantedScopes, []);
  const csrf = await worker.fetch(new Request('https://oauth.example/oauth/google/disconnect', { method: 'POST', headers: { Origin: 'https://preview.example' } }), env); assert.equal(csrf.status, 403);
  const start = await worker.fetch(new Request('https://oauth.example/oauth/google/start', { headers: { Origin: 'https://preview.example' } }), env); assert.equal(start.status, 503);
});
test('canonical persistence keys reject every sensitive naming variation', () => {
  const forbidden = ['accessToken','access_token','access-token','refreshToken','refresh_token','refresh-token','authorizationCode','authorization_code','authorization-code','oauthCode','oauth_code','clientSecret','client_secret','client-secret','googlePassword','google_password','password','codeVerifier','code_verifier','code-verifier','CodeVerifier','CODE_VERIFIER','pkceVerifier','pkce_verifier','pkce-verifier','PkceVerifier','PKCE_VERIFIER','oauthState','oauth_state','oauth-state','OAuthState','OAUTH_STATE','oauthTransactionState','oauth_transaction_state','oauth-transaction-state','OAuthTransactionState','encryptedToken','encrypted_token','encrypted-token','EncryptedToken','ENCRYPTED_TOKEN','encryptedRefreshToken','encrypted_refresh_token','encrypted-refresh-token','EncryptedRefreshToken','tokenCiphertext','token_ciphertext','token-ciphertext','TokenCiphertext'];
  for (const key of forbidden) assert.throws(() => assertNoOAuthSecrets({ [key]: 'redacted-test-value' }), /不可持久化/, key);
  assert.equal(canonicalPersistenceKey('Encrypted_Refresh-Token'), 'encryptedrefreshtoken');
});
test('persistence scanner recursively rejects root arrays and mixed nested structures', () => {
  const unsafe = [{ oauth: { codeVerifier: 'x' } }, { sessions: [{ oauthState: 'x' }] }, { security: { tokenStore: { encryptedToken: 'x' } } }, [{ profile: { pkce_verifier: 'x' } }], { items: [[{ encrypted_refresh_token: 'x' }]] }];
  for (const payload of unsafe) assert.throws(() => assertNoOAuthSecrets(payload), /不可持久化/);
  assert.equal(scanSensitivePersistenceKeys({ safe: [{ nested: { value: 1 } }] }), undefined);
});
test('exact denylist allows legitimate token and state metadata names', () => {
  const safe = { tokenCount: 3, token_count: 3, designToken: 'surface', design_token: 'surface', paginationToken: 'page', pagination_token: 'page', colorToken: 'blue', color_token: 'blue', oauthStatus: 'disconnected', oauth_status: 'disconnected', stateVersion: 1, state_version: 1, encryptedMetadata: 'display-only', encrypted_metadata: 'display-only' };
  assert.doesNotThrow(() => assertNoOAuthSecrets(safe));
});
test('backup metadata always disconnects instead of restoring a session', () => { assert.deepEqual(normalizeGmailOAuth({ status: 'connected', access_token: 'not-allowed' }), { status: 'disconnected', grantedScopes: [], lastCheckedAt: undefined }); });
