import { useMemo, useState } from 'react';
import PageFrame from './PageFrame';
import { categoryLabels, DEFAULT_CASH_FLOW_PROFILE, deriveCashFlow, formatWanInput, normalizeCashFlowProfile, parseWanInput, type CashFlowCategory, type CashFlowItem, type CashFlowProfile } from '../lib/cashFlow';
import ToolQuickNavigation from '../components/ToolQuickNavigation';

const money = (value: number | null, signed = false) => { if (value === null || !Number.isFinite(value)) return '—'; const sign = signed && value > 0 ? '+' : value < 0 ? '-' : ''; const amount = Math.abs(value); return amount >= 10000 ? `${sign}${(amount / 10000).toLocaleString('zh-TW', { maximumFractionDigits: 2 })} 萬元` : `${sign}${Math.round(amount).toLocaleString('zh-TW')} 元`; };
const percent = (value: number | null) => value === null || !Number.isFinite(value) ? '—' : `${(value * 100).toFixed(1)}%`;
const tone = (value: number | null) => value === null || value === 0 ? 'hold' : value > 0 ? 'good' : 'bad';
const uid = () => `cash-flow-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;

export default function CashFlowPage({ profile, currentCash, onSave }:{profile?: CashFlowProfile;currentCash:number | null;onSave:(profile:CashFlowProfile)=>void}) {
  const [draft, setDraft] = useState(() => normalizeCashFlowProfile(profile ?? DEFAULT_CASH_FLOW_PROFILE));
  const result = useMemo(() => deriveCashFlow(draft, currentCash), [draft, currentCash]);
  const updateWan = (key: 'monthlyIncome' | 'variableExpenseBudget' | 'monthlyInvestmentBudget', rawValue: string) => { const value = parseWanInput(rawValue); if (rawValue === '' || value !== null) setDraft(current => ({ ...current, [key]: value })); };
  const updateItem = (id:string, patch:Partial<CashFlowItem>) => setDraft(current => ({ ...current, fixedExpenses: current.fixedExpenses.map(item => item.id === id ? { ...item, ...patch } : item) }));
  const removeItem = (id:string) => { if (window.confirm('確定要刪除此固定支出項目嗎？')) setDraft(current => ({ ...current, fixedExpenses: current.fixedExpenses.filter(item => item.id !== id) })); };
  const addItem = () => setDraft(current => ({ ...current, fixedExpenses:[...current.fixedExpenses, { id:uid(), name:'', amount:0, category:'other', enabled:true }] }));
  const summary = result.status === '資料不足' ? '請先填寫每月收入，系統才可判斷目前現金流狀態。' : result.status === '赤字' ? `目前預定投資金額高於可用現金流，預估每月短缺 ${money(Math.abs(result.afterInvestment ?? 0))}。` : `扣除支出與投資後，預估每月剩餘 ${money(result.afterInvestment, true)}，現金流狀態${result.status}。`;
  const expenseGroups = Object.entries(categoryLabels).map(([category, label]) => ({ category, label, amount: draft.fixedExpenses.filter(item => item.enabled && item.category === category).reduce((total, item) => total + item.amount, 0) })).filter(item => item.amount > 0);
  return <PageFrame page="tools" title="收支與現金流中心" description="以每月必要設定掌握可投入資金、支出壓力與緊急預備金。">
    <section className="cashflow-hero"><div><p className="eyebrow">V3.9 每月財務決策</p><h2>每月現金流總覽</h2><p>{summary}</p></div><strong className={result.status === '赤字' ? 'bad' : result.status === '穩定' ? 'good' : 'warn'}>{result.status}</strong></section>
    <section className="cashflow-overview">{[['每月收入',money(draft.monthlyIncome),tone(draft.monthlyIncome)],['固定支出',money(result.fixedExpenses),'hold'],['每月生活費預算',money(draft.variableExpenseBudget),'hold'],['預定投資金額',money(draft.monthlyInvestmentBudget),'hold'],['投資後剩餘現金流',money(result.afterInvestment,true),tone(result.afterInvestment)],['儲蓄率',percent(result.savingsRate),tone(result.savingsRate)],['投資率',percent(result.investmentRate),'hold']].map(([label,value,className])=><article key={String(label)}><small>{label}</small><strong className={String(className)}>{value}</strong></article>)}</section>
    <section className="cashflow-layout"><div className="cashflow-column"><section className="card cashflow-form"><h2>每月設定</h2><WanField label="每月收入（萬元）" value={draft.monthlyIncome} onChange={value=>updateWan('monthlyIncome',value)} /><WanField label="每月生活費預算（萬元）" value={draft.variableExpenseBudget} onChange={value=>updateWan('variableExpenseBudget',value)} /><WanField label="每月預定投資金額（萬元）" value={draft.monthlyInvestmentBudget} onChange={value=>updateWan('monthlyInvestmentBudget',value)} /><label>緊急預備金目標月數<select value={draft.emergencyFundTargetMonths} onChange={event=>{const value=event.currentTarget.value;setDraft(current=>({...current, emergencyFundTargetMonths:Math.min(24, Math.max(1, Number(value) || 6))}));}}>{[3,6,9,12,18,24].map(months=><option key={months} value={months}>{months} 個月</option>)}</select></label><label>備註（選填）<textarea value={draft.notes ?? ''} onChange={event=>{const value=event.currentTarget.value;setDraft(current=>({...current,notes:value}));}} /></label><div className="actions"><button type="button" onClick={()=>onSave(normalizeCashFlowProfile(draft))}>儲存現金流設定</button><button type="button" className="small" onClick={()=>setDraft(DEFAULT_CASH_FLOW_PROFILE)}>清空設定</button></div></section>
      <section className="card"><div className="cashflow-section-title"><h2>固定支出清單</h2><button type="button" className="small" onClick={addItem}>新增項目</button></div>{draft.fixedExpenses.length === 0 ? <p className="note">尚未設定固定支出。可新增房貸／房租、信貸、保險或自訂項目。</p> : <div className="cashflow-expense-list">{draft.fixedExpenses.map(item=><article key={item.id} className={item.enabled ? '' : 'is-disabled'}><div className="cashflow-item-title"><label><input type="checkbox" checked={item.enabled} onChange={event=>{const checked=event.currentTarget.checked;updateItem(item.id,{enabled:checked});}} /> 計入每月支出</label><button type="button" className="danger small" onClick={()=>removeItem(item.id)}>刪除</button></div><label>名稱<input value={item.name} onChange={event=>{const value=event.currentTarget.value;updateItem(item.id,{name:value});}} placeholder="例如：房貸" /></label><label>分類<select value={item.category} onChange={event=>{const value=event.currentTarget.value as CashFlowCategory;updateItem(item.id,{category:value});}}>{Object.entries(categoryLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><WanField label="每月金額（萬元）" value={item.amount} onChange={rawValue=>{const amount=parseWanInput(rawValue);if(rawValue===''||amount!==null)updateItem(item.id,{amount:amount ?? 0});}} /></article>)}</div>}</section></div>
      <aside className="cashflow-column"><section className="card"><h2>緊急預備金</h2><div className="risk-data"><p><span>目標月數</span><b>{draft.emergencyFundTargetMonths} 個月</b></p><p><span>每月基本支出</span><b>{money(result.livingExpenses)}</b></p><p><span>建議預備金目標</span><b>{money(result.emergencyFundTarget)}</b></p><p><span>目前現金</span><b>{result.currentCash === null ? '未設定現金資產' : money(result.currentCash)}</b></p><p><span>距離目標差額</span><b className={tone(result.emergencyGap)}>{money(result.emergencyGap,true)}</b></p><p><span>狀態</span><b>{result.emergencyProgress === null ? '—' : result.emergencyProgress >= 1 ? '已達標' : result.emergencyProgress >= .5 ? '建立中' : '不足'}</b></p></div></section><section className="card"><h2>支出壓力指標</h2><div className="risk-data"><p><span>固定支出率</span><b>{percent(result.ratios.fixedExpenseRate)}</b></p><p><span>總支出率</span><b>{percent(result.ratios.totalExpenseRate)}</b></p><p><span>投資承受度</span><b className={tone(result.ratios.investmentCapacity)}>{money(result.ratios.investmentCapacity,true)}</b></p></div><p className="note">這些門檻僅作為現金流狀態參考，不是正式財務顧問標準。</p></section><section className="card"><h2>支出結構</h2>{expenseGroups.length === 0 && (draft.variableExpenseBudget ?? 0) <= 0 ? <p className="note">尚無啟用的生活支出資料。</p> : <div className="cashflow-bars">{[...expenseGroups,{category:'variable',label:'生活費預算',amount:draft.variableExpenseBudget ?? 0}].filter(item=>item.amount>0).map(item=><div key={item.category}><span>{item.label}<b>{money(item.amount)}</b></span><i style={{width:`${result.livingExpenses>0?Math.min(100,item.amount/result.livingExpenses*100):0}%`}} /></div>)}</div>}<p className="note">預定投資金額獨立呈現，不混入生活支出占比。</p></section></aside></section>
    <ToolQuickNavigation current="cash-flow" />
  </PageFrame>;
}
function WanField({label,value,onChange}:{label:string;value:number|null;onChange:(value:string)=>void}) { return <label>{label}<input type="number" inputMode="decimal" min="0" step="0.1" value={formatWanInput(value)} onChange={event=>{const rawValue=event.currentTarget.value;onChange(rawValue);}} /></label>; }
