import { useMemo, useState } from 'react';
import PageFrame from './PageFrame';
import ToolQuickNavigation from '../components/ToolQuickNavigation';
import { annualDividendTotals, dividendAssetName, dividendDate, dividendSources, dividendSummary, dividendYears, filterDividends, isDividendTransaction, isValidDividendDate, monthlyDividendTotals, taipeiDate } from '../lib/dividends';
import { dividendIntelligence } from '../lib/dividendIntelligence';
import { dividendAssetReferenceOptions, type DividendAssetReferenceHolding } from '../lib/dividendAssetReferences';
import type { FinancialAccount } from '../lib/financialAccounts';
import type { FinancialTransaction } from '../lib/transactions';

type HoldingOption = DividendAssetReferenceHolding & { assetClass?: 'growth' | 'defensive' };
const money = (value: number, currency = 'TWD') => `${currency === 'TWD' && Math.abs(value) >= 10000 ? `${(value / 10000).toLocaleString('zh-TW', { maximumFractionDigits: 2 })} 萬` : value.toLocaleString('zh-TW', { maximumFractionDigits: 2 })} ${currency === 'TWD' ? '元' : currency}`;
const optionalNumber = (value: string) => value.trim() === '' ? undefined : Number(value);
const inputDate = (transaction: FinancialTransaction) => dividendDate(transaction);

export default function DividendCenterPage({ accounts, holdings, transactions, onCreate, onUpdate, onDelete }: { accounts: FinancialAccount[]; holdings: HoldingOption[]; transactions: FinancialTransaction[]; onCreate: (input: Partial<FinancialTransaction>) => void; onUpdate: (id: string, patch: Partial<FinancialTransaction>) => void; onDelete: (id: string) => void }) {
  const today = taipeiDate(); const activeAccounts = accounts.filter(account => account.isActive); const [editing, setEditing] = useState<FinancialTransaction | null>(null); const [accountId, setAccountId] = useState(''); const [occurredAt, setOccurredAt] = useState(today); const [assetSymbol, setAssetSymbol] = useState(''); const [assetName, setAssetName] = useState(''); const [amount, setAmount] = useState(''); const [grossAmount, setGrossAmount] = useState(''); const [withholdingTax, setWithholdingTax] = useState(''); const [note, setNote] = useState(''); const [message, setMessage] = useState(''); const [year, setYear] = useState<'all' | 'current' | number>('all'); const [assetFilter, setAssetFilter] = useState('');
  const selectedAccount = activeAccounts.find(account => account.id === accountId); const selectedCurrency = selectedAccount?.currency || 'TWD';
  const assetOptions = useMemo(() => dividendAssetReferenceOptions(holdings, transactions), [holdings, transactions]);
  const summary = useMemo(() => dividendSummary(transactions, today), [transactions, today]); const intelligence = useMemo(() => dividendIntelligence(transactions, holdings, today), [transactions, holdings, today]); const [openMonth, setOpenMonth] = useState<number | null>(null); const years = useMemo(() => dividendYears(transactions, today), [transactions, today]); const allDividendRows = useMemo(() => transactions.filter(isDividendTransaction).slice().sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)), [transactions]);
  const filteredRows = useMemo(() => allDividendRows.filter(row => { const matchesYear = year === 'all' ? true : year === 'current' ? dividendDate(row).startsWith(today.slice(0, 4)) : dividendDate(row).startsWith(String(year)); return matchesYear && (!assetFilter || row.assetSymbol === assetFilter); }), [allDividendRows, year, assetFilter, today]);
  const selectedYear = year === 'all' ? Number(today.slice(0, 4)) : year === 'current' ? Number(today.slice(0, 4)) : year; const scopedValidRows = useMemo(() => filterDividends(transactions, { ...(year === 'all' ? {} : { year }), ...(assetFilter ? { assetSymbol: assetFilter } : {}), today }), [transactions, year, assetFilter, today]); const sourceRows = useMemo(() => dividendSources(transactions, { ...(year === 'all' ? {} : { year }), ...(assetFilter ? { assetSymbol: assetFilter } : {}), today }), [transactions, year, assetFilter, today]);
  const reset = () => { setEditing(null); setAccountId(''); setOccurredAt(today); setAssetSymbol(''); setAssetName(''); setAmount(''); setGrossAmount(''); setWithholdingTax(''); setNote(''); setMessage(''); };
  const selectAsset = (symbol: string) => { setAssetSymbol(symbol); const option = assetOptions.find(item => item.symbol === symbol); if (option?.name) setAssetName(option.name); };
  const save = () => { const gross = optionalNumber(grossAmount); const tax = optionalNumber(withholdingTax); const inputAmount = gross !== undefined && tax !== undefined ? gross - tax : Number(amount); if (!selectedAccount) return setMessage('請選擇有效的收款帳戶'); if (!isValidDividendDate(occurredAt) || occurredAt > today) return setMessage('收款日期必須有效且不得晚於今天'); if (!Number.isFinite(inputAmount) || inputAmount <= 0) return setMessage('實收股息必須是大於 0 的有限數字'); if (gross !== undefined && (!Number.isFinite(gross) || gross < 0)) return setMessage('稅前股息必須是有限且不小於 0 的數字'); if (tax !== undefined && (!Number.isFinite(tax) || tax < 0)) return setMessage('扣繳稅額必須是有限且不小於 0 的數字'); if (gross !== undefined && tax !== undefined && tax > gross) return setMessage('扣繳稅額不得大於稅前股息'); const input: Partial<FinancialTransaction> = { accountId, type: 'income', status: 'posted', amount: inputAmount, currency: selectedCurrency, categoryId: 'income-dividend', occurredAt: `${occurredAt}T00:00:00.000Z`, note, assetSymbol: assetSymbol || undefined, assetName: assetName || undefined, grossAmount: gross, withholdingTax: tax }; if (editing) onUpdate(editing.id, input); else onCreate(input); reset(); };
  const edit = (transaction: FinancialTransaction) => { setEditing(transaction); setAccountId(transaction.accountId); setOccurredAt(inputDate(transaction)); setAssetSymbol(transaction.assetSymbol || ''); setAssetName(transaction.assetName || ''); setAmount(String(transaction.amount)); setGrossAmount(transaction.grossAmount === undefined ? '' : String(transaction.grossAmount)); setWithholdingTax(transaction.withholdingTax === undefined ? '' : String(transaction.withholdingTax)); setNote(transaction.note); setMessage(''); };
  const displayAssetName = (transaction: FinancialTransaction) => transaction.assetName || assetOptions.find(item => item.symbol === transaction.assetSymbol)?.name || dividendAssetName(transaction);
  return <PageFrame page="tools" title="股息中心" description="只整理已實際收到的股息紀錄；不提供外部配息資料或未來收益預估。">
    <section className="dividend-overview" aria-label="股息摘要">{[['今年已領股息', money(intelligence.currentAmount), ''], ['今年預估股息', '—', ''], ['今年領息次數', `${intelligence.currentCount} 次`, ''], ['持有配息資產數', `${intelligence.assetCount} 檔`, ''], ['累積已收股息', money(summary.totalAmount), '']].map(([label, value]) => <article key={label}><small>{label}</small><strong>{value}</strong></article>)}</section>
    <section className="dividend-layout"><div className="dividend-column"><section className="card"><h2>每月股息日曆</h2><div className="dividend-month-grid">{intelligence.monthly.map(row => <button type="button" className="small" key={row.month} aria-expanded={openMonth === row.month} aria-controls={`dividend-month-${row.month}`} onClick={() => setOpenMonth(openMonth === row.month ? null : row.month)}>{row.month} 月｜{money(row.amount)}｜{row.count} 次</button>)}</div>{openMonth && <div id={`dividend-month-${openMonth}`} className="dividend-source-list">{intelligence.monthly[openMonth - 1].items.length ? intelligence.monthly[openMonth - 1].items.map(row => <article key={row.symbol}><strong>{row.symbol}</strong><b>{money(row.amount)}｜{row.count} 次</b></article>) : <p className="note">本月尚無股息收入。</p>}</div>}</section><section className="card"><h2>資產股息排行</h2>{intelligence.ranking.length ? <div className="dividend-source-list">{intelligence.ranking.map((row, index) => <article key={row.symbol}><strong>{index + 1}. {row.symbol}</strong><b>今年 {money(row.yearAmount)}｜歷史 {money(row.amount)}</b></article>)}</div> : <p className="note">尚無有效股息資料。</p>}</section><section className="card"><h2>股息組成</h2>{intelligence.composition.map(row => <p key={row.kind}><span>{row.kind === 'growth' ? 'ETF（既有成長 assetClass）' : row.kind === 'defensive' ? '股票（既有防守 assetClass）' : '其他'}</span><strong>{(row.ratio * 100).toFixed(1)}%</strong></p>)}<h3>股息洞察</h3>{intelligence.insights.length ? intelligence.insights.map(row => <p className="note" key={row}>{row}</p>) : <p className="note">尚無股息資料。</p>}</section></div>
    <section className="dividend-layout"><div className="dividend-column"><section className="card dividend-form"><h2>{editing ? '編輯股息紀錄' : '新增股息紀錄'}</h2><p className="note">新增、編輯與刪除都直接作用於同一筆「收入／股息」交易。</p><div className="dividend-fields"><label>收款日期<input type="date" value={occurredAt} max={today} onChange={event => setOccurredAt(event.currentTarget.value)} /></label><label>收款帳戶<select value={accountId} onChange={event => setAccountId(event.currentTarget.value)}><option value="">選擇帳戶</option>{activeAccounts.map(account => <option key={account.id} value={account.id}>{account.name}（{account.currency}）</option>)}</select></label><label>資產代號<select value={assetSymbol} onChange={event => selectAsset(event.currentTarget.value)}><option value="">未指定資產</option>{assetOptions.map(option => <option key={option.symbol} value={option.symbol}>{option.label}</option>)}</select></label><label>資產名稱<input value={assetName} onChange={event => setAssetName(event.currentTarget.value)} placeholder="未指定資產可留白" /></label><label>實收股息（{selectedCurrency}）<input type="number" min="0" inputMode="decimal" value={grossAmount !== '' && withholdingTax !== '' ? String(Math.max(0, (Number(grossAmount) || 0) - (Number(withholdingTax) || 0))) : amount} onChange={event => setAmount(event.currentTarget.value)} readOnly={grossAmount !== '' && withholdingTax !== ''} /></label><label>稅前股息（選填）<input type="number" min="0" inputMode="decimal" value={grossAmount} onChange={event => setGrossAmount(event.currentTarget.value)} /></label><label>扣繳稅額（選填）<input type="number" min="0" inputMode="decimal" value={withholdingTax} onChange={event => setWithholdingTax(event.currentTarget.value)} /></label><label className="dividend-note">備註<input value={note} onChange={event => setNote(event.currentTarget.value)} /></label></div>{message && <p className="warning-message">{message}</p>}<div className="actions"><button type="button" onClick={save}>{editing ? '儲存股息紀錄' : '新增股息紀錄'}</button>{editing && <button type="button" className="small" onClick={reset}>取消編輯</button>}</div></section>
      <section className="card"><h2>年度／月度摘要</h2><div className="dividend-annual-list">{annualDividendTotals(transactions, today).length ? annualDividendTotals(transactions, today).map(row => <p key={row.year}><span>{row.year} 年</span><strong>{money(row.amount)}</strong></p>) : <p className="note">尚無有效股息資料。</p>}</div><h3>{selectedYear} 年每月已收股息</h3><div className="dividend-month-grid">{monthlyDividendTotals(transactions, selectedYear, today).map(row => <p key={row.month}><span>{row.month} 月</span><strong>{money(row.amount)}</strong></p>)}</div></section></div>
      <div className="dividend-column"><section className="card dividend-records"><div className="dividend-section-heading"><div><h2>股息紀錄</h2><p className="note">共顯示 {filteredRows.length} 筆股息交易；待入帳、作廢或排除統計資料不會納入摘要。</p></div></div><div className="dividend-filters"><label>期間<select value={String(year)} onChange={event => setYear(event.currentTarget.value === 'all' ? 'all' : event.currentTarget.value === 'current' ? 'current' : Number(event.currentTarget.value))}><option value="all">全部</option><option value="current">本年</option>{years.map(item => <option key={item} value={item}>{item} 年</option>)}</select></label><label>資產<select value={assetFilter} onChange={event => setAssetFilter(event.currentTarget.value)}><option value="">全部資產</option>{[...new Set(allDividendRows.map(row => row.assetSymbol).filter(Boolean))].map(symbol => <option key={symbol} value={symbol}>{symbol}</option>)}</select></label></div>{filteredRows.length ? <div className="dividend-record-list">{filteredRows.map(row => <article key={row.id}><div className="dividend-record-heading"><div><strong>{row.assetSymbol || '未指定資產'}</strong><span>{displayAssetName(row)}</span></div><b>{money(row.amount, row.currency)}</b></div><dl><div><dt>收款日期</dt><dd>{inputDate(row)}</dd></div><div><dt>收款帳戶</dt><dd>{accounts.find(account => account.id === row.accountId)?.name || '已不存在帳戶'}</dd></div><div><dt>狀態</dt><dd>{row.status === 'posted' && !row.excluded ? '已入帳' : row.excluded ? '已排除統計' : row.status === 'pending' ? '待入帳' : '已作廢'}</dd></div>{row.note && <div><dt>備註</dt><dd>{row.note}</dd></div>}</dl><div className="actions"><button type="button" className="small" onClick={() => edit(row)}>編輯</button><button type="button" className="danger small" onClick={() => { if (window.confirm(`確定刪除 ${inputDate(row)} 的股息紀錄？`)) onDelete(row.id); }}>刪除</button></div></article>)}</div> : <p className="note">尚無符合篩選條件的股息紀錄。</p>}</section>
        <section className="card"><h2>股息來源分布</h2>{sourceRows.length ? <div className="dividend-source-list">{sourceRows.map(row => <article key={`${row.assetSymbol}-${row.assetName}`}><div><strong>{row.assetSymbol || '未指定資產'}</strong><span>{row.assetName}</span></div><b>{money(row.amount)}｜{(row.ratio * 100).toFixed(1)}%</b></article>)}</div> : <p className="note">此篩選期間尚無有效股息資料。</p>}<p className="note">比例分母為目前篩選期間內全部有效且已實收的股息。</p></section></div></section>
    </section><ToolQuickNavigation current="dividend-center" />
  </PageFrame>;
}
