import { Link } from 'react-router-dom';
import type { ReactNode } from 'react';
import PageFrame from './PageFrame';
import ToolQuickNavigation from '../components/ToolQuickNavigation';
import type { PortfolioRiskView } from '../lib/portfolioRisk';

const money = (value: number) => `${(Math.abs(value) / 10000).toLocaleString('zh-TW', { minimumFractionDigits: 1, maximumFractionDigits: 1 })} 萬元`;
const pct = (value: number | null) => value === null || !Number.isFinite(value) ? '不可計算' : `${value.toFixed(1)}%`;
const tone = (value: number) => value >= 2 ? 'bad' : value >= 1 ? 'warn' : 'good';
export default function PortfolioRiskPage({ view }: { view: PortfolioRiskView }) {
  const risk = view.risk;
  return <PageFrame page="tools" title="投資組合風險與配置中心" description="整合既有風險、配置、績效與報價品質資料；不提供買賣金額、股數或下單建議。">
    <section className="portfolio-risk-summary"><article className={tone(risk.overallLabel === '高風險' ? 3 : risk.overallLabel === '偏高風險' ? 2 : 0)}><small>整體風險</small><strong>{risk.overallLabel}</strong><span>最高優先：{risk.primaryRisk.title}｜{risk.primaryRisk.status}</span></article><article><small>配置偏離</small><strong>{pct(view.allocation.deviation)}</strong><span>既有門檻 {pct(view.allocation.threshold)}｜{view.allocation.thresholdReached ? '已達門檻' : '門檻內'}</span></article><article><small>現金安全</small><strong>{view.cashLoan.safetyMonths === null ? '不適用' : `${view.cashLoan.safetyMonths.toFixed(1)} 個月`}</strong><span>每月還款 {money(view.cashLoan.monthlyPayment)}</span></article><article><small>投資資產最大回撤</small><strong>{view.drawdown.canCalculate ? pct((view.drawdown.maxDrawdown ?? 0) * 100) : '不可計算'}</strong><span>僅投資資產口徑</span></article></section>
    <section className="portfolio-risk-two-column"><RiskCard title="目前／目標配置"><p className="note">所有比例分母：{view.denominatorLabel}。</p><Rows rows={[["成長資產", pct(view.current.growthPct), pct(view.target.growthPct)], ["防守資產", pct(view.current.defensivePct), pct(view.target.defensivePct)], ["現金", pct(view.current.cashPct), pct(view.target.cashPct)]]} headers={['項目','目前','目標']} /><p className="note">目標總和 {pct(view.target.totalPct)}｜{view.target.status}</p></RiskCard><RiskCard title="最高風險與資料品質"><p><b>{risk.primaryRisk.title}｜{risk.primaryRisk.status}</b></p><p className="note">{risk.primaryRisk.reason}</p><ul className="portfolio-risk-quality">{view.quality.items.length ? view.quality.items.map(item => <li key={item}>{item}</li>) : <li>核心資料品質檢查正常。</li>}</ul></RiskCard></section>
    <section className="portfolio-risk-grid"><RiskCard title="配置偏離"><Rows rows={[["成長資產偏離", pct(view.allocation.deviation), '百分點'], ["再平衡門檻", pct(view.allocation.threshold), view.allocation.thresholdReached ? '已達提醒門檻' : '尚未達門檻']]} /><p className="note">僅呈現既有偏離公式與門檻，不產生買賣金額或順序。</p></RiskCard><RiskCard title="集中度"><Rows rows={[["最大單一持股", pct(view.concentration.largestPct), view.denominatorLabel], ["前兩大", pct(view.concentration.topTwoPct), view.denominatorLabel], ["前三大", pct(view.concentration.topThreePct), view.denominatorLabel]]} /></RiskCard><RiskCard title="槓桿暴露"><Rows rows={[["槓桿資產市值", money(view.leverage.value), '依名稱／代號規則'], ["占總資產", pct(view.leverage.totalPct), view.denominatorLabel], ["占成長資產", pct(view.leverage.growthPct), '成長資產為分母']]} /><p className="note">辨識標的：{view.leverage.symbols.join('、') || '無'}。</p></RiskCard><RiskCard title="現金與借款安全"><Rows rows={[["流動現金", money(view.cashLoan.cash), '帳戶流動餘額'], ["借款餘額", money(view.cashLoan.debt), '既有借款資料'], ["每月還款", money(view.cashLoan.monthlyPayment), view.cashLoan.safetyMonths === null ? '安全月數不適用' : `可支應 ${view.cashLoan.safetyMonths.toFixed(1)} 個月`]]} /></RiskCard><RiskCard title="最大回撤與距高點"><Rows rows={[["最大回撤", view.drawdown.canCalculate ? pct((view.drawdown.maxDrawdown ?? 0) * 100) : '不可計算', '投資資產'], ["距歷史高點", view.drawdown.canCalculate ? pct((view.drawdown.distanceFromHigh ?? 0) * 100) : '不可計算', '投資資產'], ["有效快照", String(view.drawdown.snapshotCount), view.drawdown.canCalculate ? '可計算' : '資料不足']]} /></RiskCard></section>
    <section className="portfolio-risk-links"><h2>既有工具</h2><Link to="/tools/allocation-simulator">前往配置模擬器</Link><Link to="/tools/risk-center">前往既有 Risk Center</Link><Link to="/analytics">前往 Performance Center</Link><Link to="/assets">前往既有再平衡頁</Link><Link to="/tools">返回工具中心</Link></section><ToolQuickNavigation current="portfolio-risk" />
  </PageFrame>;
}
function RiskCard({ title, children }: { title: string; children: ReactNode }) { return <article className="portfolio-risk-card"><h2>{title}</h2>{children}</article>; }
function Rows({ rows, headers }: { rows: string[][]; headers?: string[] }) { return <div className="portfolio-risk-rows">{headers && <div className="head">{headers.map(item => <span key={item}>{item}</span>)}</div>}{rows.map(row => <div key={row.join('|')}>{row.map(item => <span key={item}>{item}</span>)}</div>)}</div>; }
