import { Link } from 'react-router-dom';
import PageFrame from './PageFrame';
import ToolQuickNavigation from '../components/ToolQuickNavigation';
import { deriveRebalanceRecommendation, type RebalanceRecommendationRow } from '../lib/rebalanceRecommendation';

type View = ReturnType<typeof deriveRebalanceRecommendation>;
const money = (value: number | null) => value === null ? '不可計算' : `${(Math.abs(value) / 10000).toLocaleString('zh-TW', { minimumFractionDigits: 1, maximumFractionDigits: 1 })} 萬元`;
const signedMoney = (value: number | null) => value === null ? '不可計算' : `${value > 0 ? '+' : value < 0 ? '-' : ''}${money(value)}`;
const pct = (value: number | null) => value === null || !Number.isFinite(value) ? '不可計算' : `${value.toFixed(1)}%`;

export default function RebalanceRecommendationPage({ view }: { view: View }) {
  const actionLabel = (row: RebalanceRecommendationRow) => row.action === 'buy' ? '理論增加' : row.action === 'sell' ? '理論減少' : row.action === 'blocked' ? '已停止計算' : '維持';
  return <PageFrame page="tools" title="再平衡建議中心" description="以本機資料計算個別標的理論再平衡金額；不自動下單、不預測價格或時機。">
    <section className="recommendation-summary"><article className={view.canRecommend ? 'good' : 'bad'}><small>建議狀態</small><strong>{view.canRecommend ? '可產生理論建議' : '資料不足，已停止計算'}</strong><span>{view.canRecommend ? '所有資料品質 gate 已通過。' : view.blockingReasons[0]}</span></article><article><small>目前模式</small><strong>{view.mode === 'standard' ? '標準再平衡' : '只買不賣'}</strong><span>{view.mode === 'standard' ? '買入與減少金額分開呈現。' : '最大缺口優先分配預算。'}</span></article><article><small>再平衡門檻</small><strong>{view.thresholdReached ? '已達門檻' : '未達執行門檻'}</strong><span>偏離 {pct(view.allocationDeviation)}｜超過 {pct(view.thresholdGap)}</span></article><article><small>最高優先限制</small><strong>{view.blockingReasons.length ? '請先修正資料' : '資料品質正常'}</strong><span>{view.blockingReasons.length ? view.blockingReasons.length + ' 項停止原因' : '可檢視理論金額差額。'}</span></article></section>
    <section className="recommendation-two-column"><article className="recommendation-card"><h2>目前／目標配置</h2><p className="note">所有比例分母均為總資產。</p><Metrics rows={[["成長資產", money(view.allocation.growth.currentValue), pct(view.allocation.growth.targetWeight)], ["防守持股", money(view.allocation.defensive.currentValue), pct(view.allocation.defensive.targetWeight)], ["流動現金", money(view.allocation.cash.currentValue), pct(view.cashTargetPct)]]} headers={['項目', '目前', '目標']} /><p className="note">持股目標合計 {pct(view.targetTotal)}｜現金目標 {money(view.cashTargetValue)}</p></article><article className="recommendation-card"><h2>現金與預算影響</h2>{view.mode === 'standard' ? <Metrics rows={[["現有流動現金", money(view.liquidCash), '不假設賣出可立即使用'], ["理論賣出所得", money(view.sellTotal), '僅理論金額'], ["理論買入需求", money(view.buyTotal), '未含成本'], ["現金缺口", money(view.cashShortfall), '以現有流動現金計算']]} /> : <Metrics rows={[["設定預算", money(view.availableBuyBudget), '已取預算與流動現金較小值'], ["已分配", money(view.usedBuyBudget), '最大缺口優先'], ["剩餘預算", money(view.remainingBudget), '未自動投入'], ["尚未滿足缺口", money(view.unresolvedGap), '預算不足或低配缺口']]} />}</article></section>
    <section className="recommendation-card"><h2>資產建議清單</h2><p className="note">顯示理論金額，不包含數量或下單步驟。</p><div className="recommendation-list">{view.rows.map(row => <article key={row.symbol} className={`recommendation-row ${row.action}`}><header><div><strong>{row.symbol}</strong><span>{row.name}｜{row.assetClass === 'defensive' ? '防守資產' : '成長資產'}</span></div><b>{actionLabel(row)}</b></header><Metrics rows={[["目前市值", money(row.currentValue), `目前比例 ${pct(row.currentWeight)}`], ["目標市值", money(row.targetValue), `目標比例 ${pct(row.targetWeight)}`], ["配置差額", signedMoney(row.difference), row.reason], ["建議金額", money(row.recommendedAmount), row.unresolvedAmount === null ? '資料不足，未以 0 替代' : row.unresolvedAmount > 0 ? `尚未滿足 ${money(row.unresolvedAmount)}` : '目前無未滿足缺口']]} /></article>)}</div></section>
    <section className="recommendation-two-column"><article className="recommendation-card"><h2>資料品質與停止原因</h2>{view.blockingReasons.length ? <ul className="recommendation-list-text">{view.blockingReasons.map(reason => <li key={reason}>{reason}</li>)}</ul> : <p className="note">核心資料品質 gate 已通過；最近有效交易日可顯示，但備援、過期或日期不明報價會停止具體金額建議。</p>}</article><article className="recommendation-card"><h2>限制說明</h2><ul className="recommendation-list-text">{view.limitations.map(item => <li key={item}>{item}</li>)}</ul></article></section>
    <section className="recommendation-links"><h2>既有工具</h2><Link to="/tools/portfolio-risk">投資組合風險與配置中心</Link><Link to="/tools/allocation-simulator">配置模擬器</Link><Link to="/assets">資產頁</Link><Link to="/tools">返回工具中心</Link></section><ToolQuickNavigation current="rebalance-recommendation" />
  </PageFrame>;
}
function Metrics({ rows, headers }: { rows: string[][]; headers?: string[] }) { return <div className="recommendation-metrics">{headers && <div className="head">{headers.map(item => <span key={item}>{item}</span>)}</div>}{rows.map(row => <div key={row.join('|')}>{row.map(item => <span key={item}>{item}</span>)}</div>)}</div>; }
