import { useState } from 'react';
import { Link } from 'react-router-dom';
import PageFrame from './PageFrame';
import { deriveRiskMetrics, type RiskInput } from '../lib/riskMetrics';
import { deriveRiskPresentation } from '../lib/riskPresentation';
import ToolQuickNavigation from '../components/ToolQuickNavigation';
import type { HouseholdLiquidityDiagnosticPresentation } from '../lib/householdLiquidityDiagnosticPresentation';
import HouseholdLiquidityDiagnosticList from '../components/HouseholdLiquidityDiagnosticList';
import { deriveLoanDataFreshness, LOAN_DATA_STALE_THRESHOLD_DAYS } from '../lib/loanDataFreshness';
import { displayAmount, displayEmbeddedAmounts } from '../lib/amountVisibility';
import { useAmountsHidden } from '../components/layout/AmountVisibilityContext';
import CollapseEyeIcon from '../components/CollapseEyeIcon';

const rawMoney = (value: number) => `${(Math.abs(value) / 10000).toLocaleString('zh-TW', { minimumFractionDigits: 1, maximumFractionDigits: 1 })} 萬元`;
const pct = (value: number) => `${Number.isFinite(value) ? value.toFixed(1) : '0.0'}%`;
const riskClass = (level: number) => level >= 3 ? 'bad' : level >= 2 ? 'warn' : level >= 1 ? 'hold' : 'good';
export default function RiskCenterPage({ input, diagnostics, today, onConfirmLoanFresh }: { input: RiskInput; diagnostics: HouseholdLiquidityDiagnosticPresentation; today: string; onConfirmLoanFresh: (loanId: string) => void }) {
  const hidden = useAmountsHidden();
  const money = (value: number) => displayAmount(rawMoney(value), hidden);
  const nullableMoney = (value: number | null) => value === null ? '資料不足' : money(value);
  const [showNotes, setShowNotes] = useState(false);
  const risk = deriveRiskMetrics(input);
  const presentation = deriveRiskPresentation(risk);
  // UR-TODO-041: standalone per-loan staleness indicator — deliberately not part of
  // `presentation`／`dataCompleteness`／`confidence` above, so it can never affect Plan A's
  // "no trade/AI Decision side effects" guarantee. Purely a Risk Center display concern.
  const loanFreshnessById = new Map(deriveLoanDataFreshness(risk.loans, today).map(entry => [entry.loanId, entry]));
  const cashStatus = risk.cashSafetyMonths === null ? presentation.dataStatus === '資料完整' ? '目前無必要支出壓力' : presentation.dataStatus : risk.cashSafetyMonths >= 12 ? '安全' : risk.cashSafetyMonths >= 6 ? '注意' : risk.cashSafetyMonths >= 3 ? '偏高' : '高風險';
  return <PageFrame page="tools" title="風險與現金安全中心" description="整合現金、借款、槓桿及資產集中風險，快速找出最需要優先處理的財務問題。">
    <section className={`risk-hero ${riskClass(risk.overallLevel)}`}><div><small>整體風險等級</small><h2>{risk.overallLabel}</h2><p>主要風險：{risk.primaryRisk.title}｜{displayEmbeddedAmounts(risk.primaryRisk.reason, hidden)}</p></div><strong>{risk.primaryRisk.suggestion}</strong></section>
    <section className="risk-summary-grid">{[['現金安全月數', risk.cashSafetyMonths === null ? presentation.dataStatus : `${risk.cashSafetyMonths.toFixed(1)} 個月`], ['每月必要支出', nullableMoney(presentation.monthlyEssentialExpenses)], ['現金占總資產', pct(risk.cashRatio)], ['成長／防守', `${pct(risk.growthRatio)}／${pct(risk.defensiveRatio)}`], ['借款餘額', money(risk.debt)], ['配置偏離', `${pct(risk.allocationDeviation)}｜門檻 ${pct(risk.rebalanceThreshold)}`]].map(([label, value]) => <article key={label}><small>{label}</small><strong>{value}</strong></article>)}</section>
    <section className="risk-two-column"><article className="card"><h2>現金安全分析</h2><div className="risk-data"><p><span>目前台幣現金</span><b>{money(risk.cash)}</b></p><p><span>每月必要支出</span><b>{nullableMoney(presentation.monthlyEssentialExpenses)}</b></p><p><span>最低安全現金（6 個月）</span><b>{nullableMoney(presentation.monthlyEssentialExpenses === null ? null : risk.minimumCashTarget)}</b></p><p><span>穩健安全現金（12 個月）</span><b>{nullableMoney(presentation.monthlyEssentialExpenses === null ? null : risk.stableCashTarget)}</b></p><p><span>安全存量缺口</span><b className={presentation.safetyCashShortfall === null ? 'warn' : presentation.safetyCashShortfall > 0 ? 'bad' : 'good'}>{nullableMoney(presentation.safetyCashShortfall)}{presentation.safetyCashShortfall === null ? '' : presentation.safetyCashShortfall > 0 ? ' 待補足' : ' 已補足'}</b></p><p><span>可投資現金</span><b>{nullableMoney(presentation.investableCash)}</b></p><p><span>資料可信度</span><b className={presentation.confidenceLabel === '低' ? 'warn' : presentation.confidenceLabel === '中' ? 'hold' : 'good'}>{presentation.confidenceLabel}｜{presentation.dataStatus}</b></p><p><span>現金安全狀態</span><b className={riskClass(risk.items[0].level)}>{cashStatus}</b></p></div><p className="note">{presentation.dataStatus === '資料完整' ? risk.items[0].suggestion : '請先補齊收支與現金流資料；資料不足時不會將安全存量或可投資現金視為零。'}</p>{presentation.duplicateSourceWarnings.length > 0 && <div className="warning-message"><b>重複來源警示</b>{presentation.duplicateSourceWarnings.map(message => <p key={message}>{message}</p>)}</div>}<HouseholdLiquidityDiagnosticList title="待補齊的資料來源" presentation={diagnostics} /></article><article className="card"><h2>借款安全分析</h2><div className="risk-data"><p><span>借款筆數</span><b>{risk.loans.length} 筆</b></p><p><span>借款總餘額</span><b>{money(risk.debt)}</b></p><p><span>月付壓力</span><b className={riskClass(risk.items[1].level)}>{risk.items[1].status}</b></p><p><span>6／12 月安全準備</span><b>{presentation.safetyCashShortfall === null ? '資料不足' : presentation.safetyCashShortfall > 0 ? '6 月待補足' : risk.cash >= risk.stableCashTarget ? '6／12 月充足' : '6 月充足／12 月待補足'}</b></p></div><div className="risk-loan-list">{risk.loans.length ? risk.loans.map(loan => { const freshness = loanFreshnessById.get(loan.id); return <article key={loan.id}><strong>{loan.name || '未命名借款'}</strong><span>餘額 {money(loan.principal)}｜月付 {money(loan.monthlyPayment)}｜利率 {loan.annualRate.toFixed(2)}%</span><span>剩餘 {loan.remainingMonths === undefined ? '—' : `${loan.remainingMonths} 期`}｜還款進度 {loan.totalMonths ? `${Math.min(100, ((loan.paidMonths ?? 0) / loan.totalMonths * 100)).toFixed(0)}%` : '—'}</span>{freshness?.isStale && <div className="risk-loan-stale-warning" role="status"><p>負債資料過期提醒：上次確認於 {freshness.asOf}，已超過 {LOAN_DATA_STALE_THRESHOLD_DAYS} 天。這不會影響任何買賣建議或安全存量計算，僅提醒您確認資料是否仍正確。</p><button type="button" className="small" onClick={() => onConfirmLoanFresh(loan.id)}>我已確認這筆資料仍正確</button></div>}</article>; }) : <p className="note">目前沒有借款資料。</p>}</div></article></section>
    <section className="risk-two-column"><article className="card"><h2>資產槓桿風險</h2><div className="risk-data"><p><span>槓桿型資產市值</span><b>{money(risk.leveragedValue)}</b></p><p><span>占總資產比例</span><b>{pct(risk.leveragedRatio)}</b></p><p><span>占成長資產比例</span><b>{pct(risk.leveragedGrowthRatio)}</b></p><p><span>槓桿資產數量</span><b>{risk.leveragedAssets.length} 項</b></p><p><span>風險等級</span><b className={riskClass(risk.items[2].level)}>{risk.items[2].status}</b></p></div><p className="note">槓桿資產依目前代碼及名稱規則辨識。</p></article><article className="card"><h2>資產集中度風險</h2><div className="risk-data"><p><span>最大單一資產</span><b>{risk.largest ? `${risk.largest.symbol}｜${pct(risk.largestHoldingRatio)}` : '—'}</b></p><p><span>前兩大／前三大</span><b>{pct(risk.topTwoRatio)}／{pct(risk.topThreeRatio)}</b></p><p><span>成長／防守／現金</span><b>{pct(risk.growthRatio)}／{pct(risk.defensiveRatio)}／{pct(risk.cashRatio)}</b></p><p><span>集中風險</span><b className={riskClass(risk.items[3].level)}>{risk.items[3].status}</b></p></div><p className="note">集中度門檻為一般化風險提示，不代表所有投資策略都應採相同限制。</p></article></section>
    <section className="card"><h2>成長／防守配置風險</h2><div className="risk-data risk-data-wide"><p><span>成長資產目前／目標</span><b>{pct(risk.growthRatio)}／{pct(input.growthTargetPct)}</b></p><p><span>防守資產目前比例</span><b>{pct(risk.defensiveRatio)}</b></p><p><span>現金比例</span><b>{pct(risk.cashRatio)}</b></p><p><span>偏離與門檻</span><b className={risk.thresholdReached ? 'warn' : 'good'}>{pct(risk.allocationDeviation)}｜{risk.thresholdReached ? '已超過門檻' : '在門檻內'}</b></p></div><p className="note">沿用 Analytics Center 的成長資產偏離公式與既有再平衡門檻。</p></section>
    <section className="card"><h2>風險優先處理清單</h2><ol className="risk-priority-list">{risk.priorityActions.map((item, index) => <li key={item.key}><b>{index + 1}</b><div><strong>{item.title}｜{item.status}</strong><span>{displayEmbeddedAmounts(item.reason, hidden)}</span><em>{item.suggestion}</em>{item.key === 'allocation' && <Link to="/analytics">前往分析頁查看再平衡建議</Link>}{(item.key === 'concentration' || item.key === 'leveraged') && <Link to="/tools/allocation-simulator">前往資產配置模擬器</Link>}</div></li>)}</ol></section>
    <section className="card risk-notes"><button type="button" className="section-toggle" aria-expanded={showNotes} onClick={() => setShowNotes(current => !current)}><span>風險說明與資料限制</span><b className="section-toggle-eye">{showNotes ? '收合' : '展開'} <CollapseEyeIcon open={showNotes} /></b></button>{showNotes && <div className="section-content"><p>整體風險採核心項目中的最高等級：現金安全、借款壓力、槓桿資產、單一資產集中度及配置偏離。</p><p>現金安全月數 = 現金 ÷ 每月必要支出（生活費＋借款還款）。資料不足時不顯示月數，也不將安全存量或可投資現金當作零。</p><p>最大單一資產低於 30% 為低、30%～50% 為中、50%～70% 為偏高、超過 70% 為高。本頁為一般化風險提示，不是保證或個人化投資建議。</p></div>}</section>
    <ToolQuickNavigation current="risk-center" />
  </PageFrame>;
}
