const encoder = new TextEncoder();
const b64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
export const randomUrl = (length = 48) => b64(crypto.getRandomValues(new Uint8Array(length)));
export async function pkce() { const verifier = randomUrl(64); const digest = await crypto.subtle.digest('SHA-256', encoder.encode(verifier)); return { verifier, challenge: b64(new Uint8Array(digest)), method: 'S256' as const }; }
export type Transaction = { state: string; codeVerifier: string; redirectTarget: string; audience: string; createdAt: number; expiresAt: number; consumedAt?: number };
export type OAuthSession = { expiresAt: number; audience: string; scopes: string[]; encryptedToken?: string };
export interface OAuthStore { createOAuthTransaction(redirectTarget: string, audience: string, verifier: string): Transaction; consumeOAuthTransaction(state: string): Transaction; createSession(audience: string, scopes: string[], encryptedToken?: string): string; getSession(id: string, audience: string): OAuthSession | undefined; deleteSession(id: string): void; }
export class MemorySessionStore implements OAuthStore { private transactions = new Map<string, Transaction>(); private sessions = new Map<string, OAuthSession>(); createOAuthTransaction(redirectTarget: string, audience: string, verifier: string) { const state = randomUrl(); const transaction = { state, codeVerifier: verifier, redirectTarget, audience, createdAt: Date.now(), expiresAt: Date.now() + 600000 }; this.transactions.set(state, transaction); return transaction; } consumeOAuthTransaction(state: string) { const t = this.transactions.get(state); if (!t) throw new Error('oauth_invalid_state'); if (t.consumedAt) throw new Error('oauth_replay_detected'); if (t.expiresAt < Date.now()) throw new Error('oauth_state_expired'); t.consumedAt = Date.now(); return t; } createSession(audience: string, scopes: string[], encryptedToken?: string) { const id = randomUrl(); this.sessions.set(id, { expiresAt: Date.now() + 3600000, audience, scopes, encryptedToken }); return id; } getSession(id: string, audience: string) { const s = this.sessions.get(id); return s && s.audience === audience && s.expiresAt > Date.now() ? s : undefined; } deleteSession(id: string) { this.sessions.delete(id); } }
/** Production adapter boundary only. A durable binding is deliberately not configured in V4.4. */
export class ProductionSessionStoreAdapter implements OAuthStore { private unavailable(): never { throw new Error('oauth_production_store_not_configured'); } createOAuthTransaction(): Transaction { return this.unavailable(); } consumeOAuthTransaction(): Transaction { return this.unavailable(); } createSession(): string { return this.unavailable(); } getSession(): OAuthSession | undefined { return this.unavailable(); } deleteSession(): void { this.unavailable(); } }
export async function encryptToken(token: string, keyText: string) { const key = await crypto.subtle.importKey('raw', new Uint8Array(await crypto.subtle.digest('SHA-256', encoder.encode(keyText))), 'AES-GCM', false, ['encrypt']); const iv = crypto.getRandomValues(new Uint8Array(12)); const encrypted = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, encoder.encode(token)); return `${b64(iv)}.${b64(new Uint8Array(encrypted))}`; }
